import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import NextLink from "next/link";
import { Flex, Box, Container, Link } from "@chakra-ui/react";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Real Estate App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box boxShadow='0 0 4px #dadada'>
        <Flex justifyContent='space-around' alignItems='center'>
          <h4 className='logo'>RealEstate</h4>
          <Flex justifyContent='space-around' alignItems='center'>
            <NextLink href='/' passHref>
              <Link
                marginRight='15px'
                height={60}
                display='flex'
                alignItems='center'
                p='0 15px'
                background='#dedeff87'
                borderTop='2px solid #4995d3'
              >
                Home
              </Link>
            </NextLink>
            <NextLink href='/' passHref>
              <Link
                marginRight='15px'
                height={60}
                display='flex'
                alignItems='center'
              >
                For Sale
              </Link>
            </NextLink>
            <NextLink href='/' passHref>
              <Link
                marginRight='15px'
                height={60}
                display='flex'
                alignItems='center'
              >
                For Rent
              </Link>
            </NextLink>
          </Flex>
        </Flex>
      </Box>
      <Container maxW='md'>
        <Box minHeight='calc(100vh - 149px)'>{children}</Box>
      </Container>

      <Box
        display='flex'
        justifyContent='center'
        alignItems='center'
        p='2rem 0'
        borderTop='1px solid #eaeaea'
      >
        <p>Made with love by samyscode</p>
      </Box>
    </div>
  );
};
export default Layout;
